
import { ResultData } from '@/types/assessment';

export interface EmailData {
  to: string;
  subject: string;
  html: string;
}

export const generateResultsEmail = (result: ResultData, userEmail: string): EmailData => {
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Your Behavioral Assessment Results</title>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: linear-gradient(135deg, #f97316 0%, #fb923c 100%); color: white; padding: 30px; text-align: center; border-radius: 12px; margin-bottom: 30px; }
        .section { background: #fef7ed; padding: 25px; margin: 20px 0; border-radius: 12px; border-left: 5px solid #f97316; }
        .stress-level { font-size: 24px; font-weight: bold; color: #f97316; }
        .strategy { background: white; padding: 15px; margin: 10px 0; border-radius: 8px; border-left: 3px solid #fb923c; }
        .footer { text-align: center; margin-top: 40px; padding: 20px; color: #666; font-size: 14px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>🧠 Your Behavioral Profile Results</h1>
        <p>Based on scientific assessment and AI analysis</p>
      </div>

      <div class="section">
        <h2>🎯 Stress Susceptibility</h2>
        <div class="stress-level">Level: ${result.stressLevel}</div>
        <p><strong>Score:</strong> ${result.stressScore}%</p>
        <p>${result.stressDescription}</p>
      </div>

      <div class="section">
        <h2>💫 Personality Tendencies</h2>
        <p><strong>Social Tendency:</strong> ${result.personalityType}</p>
        <p><strong>Confidence Level:</strong> ${result.confidence}%</p>
        <p>${result.personalityDescription}</p>
      </div>

      <div class="section">
        <h2>🛡️ Personalized Coping Strategies</h2>
        ${result.copingStrategies.map(strategy => `
          <div class="strategy">
            <h4>${strategy.title}</h4>
            <p>${strategy.description}</p>
          </div>
        `).join('')}
      </div>

      <div class="footer">
        <p><strong>Remember:</strong> This assessment is for educational and self-reflection purposes only.</p>
        <p>If you're experiencing significant stress, please consult a qualified professional.</p>
        <hr style="margin: 20px 0; border: none; border-top: 1px solid #ddd;">
        <p>Generated by Behavioral Assessment AI | Take the test again at our website</p>
      </div>
    </body>
    </html>
  `;

  return {
    to: userEmail,
    subject: '🧠 Your Behavioral Assessment Results - Personal Insights & Coping Strategies',
    html
  };
};

export const sendEmail = async (emailData: EmailData): Promise<{ success: boolean; message: string }> => {
  try {
    // Using EmailJS for client-side email sending
    // In a real application, you'd want to use a backend service
    const response = await fetch('https://api.emailjs.com/api/v1.0/email/send', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        service_id: 'default_service', // This would need to be configured
        template_id: 'template_results', // This would need to be configured  
        user_id: 'your_user_id', // This would need to be configured
        template_params: {
          to_email: emailData.to,
          subject: emailData.subject,
          html_content: emailData.html,
        }
      }),
    });

    if (response.ok) {
      return { success: true, message: 'Email sent successfully!' };
    } else {
      throw new Error('Failed to send email');
    }
  } catch (error) {
    console.error('Email sending error:', error);
    return { 
      success: false, 
      message: 'Unable to send email at the moment. Please screenshot your results.' 
    };
  }
};
